/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * Health check endpoint
     * @description Returns the health status of the API
     */
    get: {
      responses: {
        /** @description API is healthy */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
            };
          };
        };
      };
    };
  };
  "/pos/sessions": {
    /**
     * Create a new cashier session
     * @description Creates a new POS session for a cashier. Terminal is inferred from the Bearer token.
     * If `mode` is omitted, the session is created with `mode=UNSET` and the Buyer selects the mode after FACE_VERIFIED.
     */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** @example cs_1 */
            cashier_id: string;
            /**
             * @example PURCHASE
             * @enum {string|null}
             */
            mode?: "PURCHASE" | "REDEEM" | null;
          };
        };
      };
      responses: {
        /** @description Session created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["TerminalDisabled"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/amount": {
    /**
     * Set purchase amount
     * @description Sets the purchase amount for PURCHASE mode sessions
     */
    post: {
      parameters: {
        path: {
          sessionId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example 10000 */
            amount_cents: number;
          };
        };
      };
      responses: {
        /** @description Amount set successfully */
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["TerminalDisabled"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["IdempotencyConflict"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/reward": {
    /**
     * Set reward for redemption
     * @description Sets the reward for REDEEM mode sessions
     */
    post: {
      parameters: {
        path: {
          sessionId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example r_1 */
            reward_id: string;
          };
        };
      };
      responses: {
        /** @description Reward set successfully */
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["TerminalDisabled"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["IdempotencyConflict"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/face-scan": {
    /**
     * Perform face scan verification
     * @description Verifies the buyer's face using biometric authentication.
     * On success, updates the session to FACE_VERIFIED and enriches the session snapshot with:
     * - user.first_name / user.last_name (from `users`)
     * - merchant_name + user.points for the session merchant
     * Requires Idempotency-Key header.
     */
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
        path: {
          sessionId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: base64
             * @description Base64 encoded face image
             */
            imageBase64?: string;
            /** @description Alternative token-based face verification (future use) */
            faceToken?: string;
          };
        };
      };
      responses: {
        /** @description Face verification successful */
        200: {
          content: {
            "application/json": {
              /**
               * @example VERIFIED
               * @enum {string}
               */
              status?: "VERIFIED";
              /** @example user-123 */
              user_id?: string;
              /** @example face-456 */
              face_id?: string;
              /**
               * Format: float
               * @example 0.95
               */
              similarity?: number;
              session?: components["schemas"]["SessionResponse"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["TerminalDisabled"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["IdempotencyConflict"];
        500: components["responses"]["InternalServerError"];
        503: components["responses"]["BiometricUnavailable"];
        504: components["responses"]["BiometricTimeout"];
      };
    };
  };
  "/pos/sessions/{sessionId}/mode": {
    /**
     * Select mode after face verification (buyer step)
     * @description Buyer selects session mode after FACE_VERIFIED. Sets mode and enriches the session snapshot with merchant_name and the user's points balance for that merchant.
     * Requires Idempotency-Key header.
     */
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
        path: {
          sessionId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SetModeRequest"];
        };
      };
      responses: {
        /** @description Mode selected */
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["IdempotencyConflict"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/purchase/commit": {
    /**
     * PURCHASE single-commit (amount + confirm + close)
     * @description Recommended PURCHASE flow. Parses a human amount string into cents, commits the purchase, and closes the session in a single atomic operation.
     * Requires Idempotency-Key header.
     */
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
        path: {
          sessionId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PurchaseCommitRequest"];
        };
      };
      responses: {
        /** @description Purchase committed and session closed */
        200: {
          content: {
            "application/json": components["schemas"]["PurchaseCommitResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["IdempotencyConflict"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/redeem/select": {
    /**
     * REDEEM select reward (generates voucher_code)
     * @description Buyer selects a reward for a REDEEM session. Generates a voucher_code and moves the session to READY_TO_CONFIRM.
     * Requires Idempotency-Key header.
     */
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
        path: {
          sessionId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RedeemSelectRequest"];
        };
      };
      responses: {
        /** @description Reward selected */
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["IdempotencyConflict"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/redeem/commit": {
    /**
     * REDEEM commit (confirm + close)
     * @description Vendor confirms a REDEEM session that is READY_TO_CONFIRM. Commits redemption and closes session in one atomic operation.
     * Requires Idempotency-Key header.
     */
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
        path: {
          sessionId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Redemption committed and session closed */
        200: {
          content: {
            "application/json": components["schemas"]["RedeemCommitResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["IdempotencyConflict"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/confirm": {
    /**
     * Confirm and commit transaction
     * @description Commits the transaction (purchase or redemption). Requires Idempotency-Key header.
     */
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
        path: {
          sessionId: string;
        };
      };
      responses: {
        /** @description Transaction confirmed successfully */
        200: {
          content: {
            "application/json": components["schemas"]["ConfirmResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["TerminalDisabled"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["Conflict"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/events-ticket": {
    /**
     * Issue SSE ticket
     * @description Generates a ticket for EventSource connections, valid for the session lifetime.
     */
    post: {
      parameters: {
        path: {
          sessionId: string;
        };
      };
      responses: {
        /** @description Ticket issued successfully */
        200: {
          content: {
            "application/json": components["schemas"]["SseTicketResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/events": {
    /**
     * Session events stream (SSE)
     * @description Server-Sent Events stream for session updates. Requires a valid SSE ticket in the query param.
     */
    get: {
      parameters: {
        query: {
          /** @description SSE ticket */
          ticket: string;
        };
        path: {
          sessionId: string;
        };
      };
      responses: {
        /** @description SSE stream established */
        200: {
          content: {
            "text/event-stream": string;
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/pos/terminals/events-ticket": {
    /**
     * Issue terminal SSE ticket
     * @description Generates a ticket for terminal EventSource connections.
     */
    post: {
      responses: {
        /** @description Ticket issued successfully */
        200: {
          content: {
            "application/json": components["schemas"]["SseTicketResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["TerminalDisabled"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/terminals/events": {
    /**
     * Terminal events stream (SSE)
     * @description Server-Sent Events stream for terminal updates. Requires a valid SSE ticket in the query param.
     * Events: connected, terminal_state, current_session, session_created, session_updated, session_closed, heartbeat.
     */
    get: {
      parameters: {
        query: {
          /** @description SSE ticket */
          ticket: string;
        };
      };
      responses: {
        /** @description SSE stream established */
        200: {
          content: {
            "text/event-stream": string;
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
  };
  "/pos/sessions/{sessionId}/close": {
    /**
     * Close session
     * @description Closes an active session
     */
    post: {
      parameters: {
        path: {
          sessionId: string;
        };
      };
      responses: {
        /** @description Session closed successfully */
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["TerminalDisabled"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/sessions/{sessionId}/cancel": {
    /**
     * Cancel session (force CANCELLED)
     * @description Cancels a session regardless of its current status. Sets status=CANCELLED, emits SSE, clears terminal current session if needed,
     * and deletes the session from Redis (no record kept). Requires Idempotency-Key header.
     */
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
        path: {
          sessionId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Session cancelled */
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["IdempotencyConflict"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
  "/pos/rewards": {
    /**
     * List rewards for authenticated merchant
     * @description Returns ACTIVE rewards for the merchant associated with the authenticated terminal. Disabled rewards are not returned.
     * If `session_id` is provided (and the session has a verified user), items include `can_redeem` per reward for that user.
     */
    get: {
      parameters: {
        query?: {
          /** @description Optional POS session id to compute per-user redeemability (`can_redeem`) */
          session_id?: string;
        };
      };
      responses: {
        /** @description Rewards list */
        200: {
          content: {
            "application/json": components["schemas"]["RewardsListResponse"];
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalServerError"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SseTicketResponse: {
      /** @description SSE ticket */
      ticket: string;
      /** @example 60 */
      expires_in_seconds: number;
    };
    SessionResponse: {
      /** Format: uuid */
      session_id?: string;
      merchant_id?: string;
      merchant_name?: string | null;
      terminal_id?: string;
      cashier_id?: string;
      /** @enum {string} */
      mode?: "UNSET" | "PURCHASE" | "REDEEM";
      /** @enum {string} */
      status?: "OPEN" | "WAITING_FACE" | "FACE_VERIFIED" | "WAITING_ACTION" | "READY_TO_CONFIRM" | "COMMITTING" | "COMMITTED" | "CLOSED" | "CANCELLED" | "EXPIRED" | "FAILED";
      user?: ({
        user_id?: string;
        first_name?: string | null;
        last_name?: string | null;
        points?: number | null;
        face_id?: string | null;
        /** Format: float */
        similarity?: number | null;
        /** Format: date-time */
        verified_at?: string | null;
      }) | null;
      purchase?: {
        amount_cents?: number;
      } | null;
      redeem?: ({
        reward_id?: string;
        voucher_code?: string;
        reward_name?: string | null;
        reward_description?: string | null;
      }) | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      expires_at?: string;
      /** Format: date-time */
      closed_at?: string | null;
    };
    PurchaseCommitRequest: {
      /**
       * @description Human decimal amount string (e.g. "1234", "1234.5", "1234.50")
       * @example 1234.50
       */
      amount: string;
      /**
       * @description Optional currency code for future use (ignored for now)
       * @example UYU
       */
      currency?: string | null;
    };
    PurchaseCommitResponse: components["schemas"]["ConfirmResponse"] & {
      session: components["schemas"]["SessionResponse"];
    };
    RedeemSelectRequest: {
      /** @description Reward ID to redeem */
      reward_id: string;
    };
    SetModeRequest: {
      /** @enum {string} */
      mode: "PURCHASE" | "REDEEM";
    };
    RedeemCommitResponse: components["schemas"]["ConfirmResponse"] & {
      session: components["schemas"]["SessionResponse"];
    };
    ConfirmResponse: {
      transaction_id?: string;
      /** @enum {string} */
      status?: "COMMITTED";
      points_delta?: number;
      redemption_id?: string | null;
      voucher_code?: string | null;
    };
    Reward: {
      id?: string;
      merchant_id?: string;
      name?: string;
      description?: string | null;
      cost_points?: number;
      /** @enum {string} */
      status?: "ACTIVE" | "DISABLED";
      /** Format: date-time */
      created_at?: string;
      /** @description If true, the same user can redeem this reward multiple times. */
      is_repeatable?: boolean;
      /** @description If `session_id` is provided, indicates whether the current session user can redeem this reward. */
      can_redeem?: boolean | null;
    };
    RewardsListResponse: {
      items: components["schemas"]["Reward"][];
    };
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        request_id: string;
      };
    };
  };
  responses: {
    /** @description Invalid payload or validation error */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Request body validation failed */
    ValidationError: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Terminal is disabled */
    TerminalDisabled: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Resource not found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Conflict */
    Conflict: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Idempotency key conflict */
    IdempotencyConflict: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Biometric service unavailable */
    BiometricUnavailable: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Biometric service timeout */
    BiometricTimeout: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Internal server error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
